import type { Metadata } from "next";
import Header from "./Components/Header/header";
import "./globals.css";
import Footer from "./Components/Footer/footer";
import { InfoProvider } from "./Components/ContextProvider/contextProvider";
export const metadata: Metadata = {
  title: "AutoCatalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <InfoProvider>
        <body>
          <main>{children}</main>
          <Footer />
        </body>
      </InfoProvider>
    </html>
  );
}
