import type { Metadata } from "next";
import Header from "./Components/Header/header";
import "./globals.css";
import Footer from "./Components/Footer/footer";
export const metadata: Metadata = {
  title: "AutoCatalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
